### DISCUSSION TITLE
Fastest possible sync for development purposes

### DISCUSSION THREAD

**Discussion by dav1app** [lightningnetwork/lnd#8016] [Q&A]
Hi everybody,

I'm seeking to use `lnd` Docker image for testing purposes. It will monitor future transactions after `lnd` is launched, using RPC. One of the requirements is that the node should be ephemeral - I can easily create and destroy the docker images, so I'm struggling with sync.

How can I achieve the fastest possible sync/startup time? No need to use any historical data or anything prior. 

Currently, I'm trying with this. Neutrino isn't mandatory. 

```
  lnd-testnet:
    image: lightninglabs/lnd:v0.17.0-beta.rc4
    command:
      - "--bitcoin.active"
      - "--bitcoin.testnet"
      - "--bitcoin.node=neutrino"
      - "--neutrino.maxpeers=1"
      - "--routing.assumechanvalid"
      - "--rpclisten=0.0.0.0:10009"
 ```
