### ISSUE TITLE
[LOW PRIORITY!] grpc: connection is unavailable after create wallet?

### ISSUE THREAD

**Issue by ckcollab** [lightningnetwork/lnd#582]
Heyo -- thanks for all the hard work! 

So I'm going off the docker examples, re-doing it from scratch to help myself learn, and I finally have LND and BTCD running...! However, after finally getting it to find `rpc.cert` (even though it should be using user/pass?) and `lncli create` seeming to work, I get this:

```bash
root@ae3f0b30e4e8:/go/src/github.com/lightningnetwork/lnd# lncli create
Input wallet password: 
Confirm wallet password: 
root@ae3f0b30e4e8:/go/src/github.com/lightningnetwork/lnd# lncli walletbalance
[lncli] rpc error: code = Unavailable desc = grpc: the connection is unavailable
root@ae3f0b30e4e8:/go/src/github.com/lightningnetwork/lnd# lncli getinfo
[lncli] rpc error: code = Unavailable desc = grpc: the connection is unavailable
```

Here's what I have for my `docker-compose.yml` with images based on your existing docker setup:

```yaml
btcd:
  image: ckcollab/btcd
  command: btcd --testnet --rpcuser=kek --rpcpass=kek
  ports:
    # Mainnet ports
    # - 8333:8333
    # Testnet ports
    - 18333:18333
  volumes:
    - ~/.rpc_shared/:/rpc/
    - ~/.btcd/:/root/.btcd/
    - ~/.btcctl/:/root/.btcctl/

lnd:
  image: ckcollab/lnd
  command: lnd --bitcoin.active --bitcoin.testnet --bitcoin.rpcuser=kek --bitcoin.rpcpass=kek
  volumes:
    - ~/.rpc_shared/:/rpc/
    - ~/.btcd/:/root/.btcd/
    - ~/.lnd/:/root/.lnd/
```

I may be completely misunderstanding how this all ties together, if so, apologies :(
