### ISSUE TITLE
LND spamming "out of order block"

### ISSUE THREAD

**Issue by ckcollab** [lightningnetwork/lnd#589]
lnd is spamming "out of order block" over and over and over and over?

```
lnd_1   | 2018-01-10 20:31:25.193 [DBG] BTCN: Rescan got out of order block 0000000000300c890e124e7f8f1196b1d2aefe77c47762f2f0e2f7f868c81244 with prevblock 0000000000373483db33b051a83d4dccb2df985f5605d9cb90f262cb3071d51b
lnd_1   | 2018-01-10 20:31:25.194 [DBG] BTCN: Rescan got out of order block 000000000023b6325f0bec9b90e9c7fdb67effb63ee10ce38b907007871b3b72 with prevblock 0000000000300c890e124e7f8f1196b1d2aefe77c47762f2f0e2f7f868c81244
lnd_1   | 2018-01-10 20:31:25.194 [DBG] BTCN: Rescan got out of order block 0000000000315d51e4764b37877a284e2e373803f39e8ca3b2e1d87d1e24d45b with prevblock 000000000023b6325f0bec9b90e9c7fdb67effb63ee10ce38b907007871b3b72
lnd_1   | 2018-01-10 20:31:25.195 [DBG] BTCN: Rescan got out of order block 00000000001ce3fdeae58f45250f71695dc60770b1048b01c270beceb3a738d5 with prevblock 0000000000315d51e4764b37877a284e2e373803f39e8ca3b2e1d87d1e24d45b
lnd_1   | 2018-01-10 20:31:25.195 [DBG] BTCN: Rescan got out of order block 00000000000673a3f4bc6601be0efe2ab4dfb1e067fa50602c8b02410bcf57aa with prevblock 00000000001ce3fdeae58f45250f71695dc60770b1048b01c270beceb3a738d5
lnd_1   | 2018-01-10 20:31:25.196 [DBG] BTCN: Rescan got out of order block 00000000002fd64032869a4d474bf7769fcf5bbc196cf30644d67fb92289fcd2 with prevblock 00000000000673a3f4bc6601be0efe2ab4dfb1e067fa50602c8b02410bcf57aa
lnd_1   | 2018-01-10 20:31:25.197 [DBG] BTCN: Rescan got out of order block 000000000031bac29515079ae00f0001fb1ecbe4126a17945df27a6d6595f85c with prevblock 00000000002fd64032869a4d474bf7769fcf5bbc196cf30644d67fb92289fcd2
lnd_1   | 2018-01-10 20:31:25.198 [DBG] BTCN: Rescan got out of order block 00000000002ebeb28cfa3475f7219f3ad46a33fcf737008e1967fa1a7f8e316d with prevblock 000000000031bac29515079ae00f0001fb1ecbe4126a17945df27a6d6595f85c
lnd_1   | 2018-01-10 20:31:25.198 [DBG] BTCN: Rescan got out of order block 00000000003690cebf403bc21665d58a19da7186900a41f3a51e505f37d12dc3 with prevblock 00000000002ebeb28cfa3475f7219f3ad46a33fcf737008e1967fa1a7f8e316d
lnd_1   | 2018-01-10 20:31:25.199 [DBG] BTCN: Rescan got out of order block 00000000002c22ba117bc28518c29bad11b20aa0abb84148068dc37ddf5b61c3 with prevblock 00000000003690cebf403bc21665d58a19da7186900a41f3a51e505f37d12dc3
lnd_1   | 2018-01-10 20:31:25.199 [DBG] BTCN: Rescan got out of order block 00000000001e01e1f35de171fd6452e79a74fefbe4b4a9d197405b337d1fa3d5 with prevblock 00000000002c22ba117bc28518c29bad11b20aa0abb84148068dc37ddf5b61c3
lnd_1   | 2018-01-10 20:31:25.200 [DBG] BTCN: Rescan got out of order block 00000000001a687c504169dd7573aa26825208a49ba8ae67f7f6b69d90f183cc with prevblock 00000000001e01e1f35de171fd6452e79a74fefbe4b4a9d197405b337d1fa3d5
lnd_1   | 2018-01-10 20:31:25.201 [DBG] BTCN: Rescan got out of order block 000000000033923741c4fbfabae0079216ba88db188d74c1a105cc1a19d02d4d with prevblock 00000000001a687c504169dd7573aa26825208a49ba8ae67f7f6b69d90f183cc
lnd_1   | 2018-01-10 20:31:25.202 [DBG] BTCN: Rescan got out of order block 0000000000056a61e88368b411b06594144b7f6547a9ab8c11984d0b6a9d4777 with prevblock 000000000033923741c4fbfabae0079216ba88db188d74c1a105cc1a19d02d4d
lnd_1   | 2018-01-10 20:31:25.203 [DBG] BTCN: Rescan got out of order block 0000000000353e844fff8ff518e8f04b94ed4cc0d1045a2b075347364f2d6217 with prevblock 0000000000056a61e88368b411b06594144b7f6547a9ab8c11984d0b6a9d4777
lnd_1   | 2018-01-10 20:31:25.204 [DBG] BTCN: Rescan got out of order block 0000000000020e97fe0a6f65bd81cd867cb4f16199cc1282891002b438287500 with prevblock 0000000000353e844fff8ff518e8f04b94ed4cc0d1045a2b075347364f2d6217
lnd_1   | 2018-01-10 20:31:25.204 [DBG] BTCN: Rescan got out of order block 00000000000bf79c9457cffc46d183e19884f675058fc4c65ee307d935682b3f with prevblock 0000000000020e97fe0a6f65bd81cd867cb4f16199cc1282891002b438287500
lnd_1   | 2018-01-10 20:31:25.205 [DBG] BTCN: Rescan got out of order block 00000000001dd8b0dd53c87d94f522e2f000fd0b640dc4ec67153b938d77d77e with prevblock 00000000000bf79c9457cffc46d183e19884f675058fc4c65ee307d935682b3f
```

Here is my `docker-compose.yml` currently:

```yaml
btcd:
  image: ckcollab/btcd
  command: btcd --testnet --rpcuser=kek --rpcpass=kek
  ports:
    # Mainnet ports
    # - 8333:8333
    # Testnet ports
    - 18333:18333
    - 18334:18334
  environment:
    - NETWORK=testnet3
    - RPCUSER=kek
    - RPCPASS=kek
  volumes:
    - ~/.rpc_shared/:/rpc/
    - ~/.btcd/:/root/.btcd/
    - ~/.btcctl/:/root/.btcctl/

lnd:
  image: ckcollab/lnd
  command: lnd --bitcoin.active --bitcoin.testnet --bitcoin.rpcuser=kek --bitcoin.rpcpass=kek --debuglevel=debug --neutrino.active --neutrino.connect=faucet.lightning.community
  environment:
    - NETWORK=testnet3
    - RPCUSER=kek
    - RPCPASS=kek
  volumes:
    - ~/.rpc_shared/:/rpc/
    - ~/.btcd/:/root/.btcd/
    - ~/.lnd/:/root/.lnd/

```

Some recent output from `btcd`:

```bash
btcd_1  | 2018-01-10 20:25:08.088 [INF] SYNC: Lost peer 78.109.28.65:18333 (outbound)
btcd_1  | 2018-01-10 20:25:08.122 [INF] SYNC: New valid peer 192.241.158.203:18333 (outbound) (/Satoshi:0.15.0/)
btcd_1  | 2018-01-10 20:25:08.371 [INF] SYNC: New valid peer 45.56.110.70:18333 (outbound) (/Satoshi:0.14.2(bitcore)/UASF-Segwit:0.3(BIP148)/)
btcd_1  | 2018-01-10 20:25:08.371 [INF] SYNC: New valid peer 52.79.215.241:18333 (outbound) (/Satoshi:0.15.1/)
btcd_1  | 2018-01-10 20:25:22.291 [ERR] PEER: Can't read message from 165.227.7.29:18333 (outbound): read tcp 172.17.0.3:59258->165.227.7.29:18333: read: connection reset by peer
btcd_1  | 2018-01-10 20:25:22.292 [INF] SYNC: Lost peer 165.227.7.29:18333 (outbound)
btcd_1  | 2018-01-10 20:25:22.961 [INF] SYNC: New valid peer 136.144.168.213:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
btcd_1  | 2018-01-10 20:25:38.129 [INF] SYNC: New valid peer 158.109.79.23:18333 (outbound) (/Satoshi:0.15.0.1/)
btcd_1  | 2018-01-10 20:33:34.076 [INF] SYNC: Processed 1 block in the last 16m22.41s (67 transactions, height 1258339, 2018-01-10 20:33:21 +0000 UTC)```

EDIT:

Re-ran the server and it's just stuck at `Initialzing btcd backed fee estimator` after i `lncli unlock`'d the wallet. I think after I try to open a channel is when the spamming problems start..?
