### ISSUE TITLE
Socks issue when connecting to node over Tor

### ISSUE THREAD

**Issue by mllnd** [lightningnetwork/lnd#6087]
### Background

For some reason, I am unable to create a peer connection over Tor.  `lncli connect` is resulting in an ambiguous Socks error. I have access to both of the nodes (connecting side and the one where the connection is being made to).

On the connecting side, I am able to connect to other nodes over Tor. It is my other node that I am unable to connect to for some reason. I tried debugging on both ends, but not getting any meaningful output in the logs, even if `debuglevel` is increased.

To make things even more interesting, I'm able to connect to other nodes over Tor from the node I am unable to connect to.

Would be very grateful for any tips on how to debug this further. I'm more than convinced that it is an issue with the configuration, might just need a few pointers.

### Environment

* Ubuntu 20.04 LTS
* `lnd` - `v0.14.1-beta`
* `bitcoind` - `v22.0`
* `tor` - `v0.4.6.7`

### Steps to reproduce

**On the target node side**

 I'm using a custom Docker setup with the following configuration (shortened) - 

```
version: "3.5"
services:
  lnd:
    image: lightninglabs/lnd:v0.14.1-beta
    container_name: lnd
    restart: unless-stopped
    depends_on:
      - bitcoind
      - tor
    networks:
      - ln-network
    ports:
      - 9735:9735
    volumes:
      - ./mount/ssd/lnd:/root/.lnd
  tor:
    image: osminogin/tor-simple:0.4.6.7
    container_name: tor
    restart: unless-stopped
    networks:
      - ln-network
    volumes:
      - ./mount/ssd/tor:/var/lib/tor
      - ./mount/ssd/tor-config:/etc/tor
      - ./mount/ssd/tor-data:/srv/tor
networks:
  ln-network:
```

Also `torrc` configuration:

```
# Bound to external interface to be able to communicate with other containers
SocksPort 0.0.0.0:9050
ControlPort 0.0.0.0:9051
Log notice stdout
ExitRelay 0
```

And `lnd.conf`:

```
[tor]
tor.active=true
tor.v3=true
tor.streamisolation=false
tor.privatekeypath=[keypath]
tor.socks=tor:9050
tor.control=tor:9051
tor.password=[removed]
tor.skip-proxy-for-clearnet-targets=true
```

### Expected behaviour

Should be able to connect to to the target node over Tor.

### Actual behaviour

Tor connection fails with error message:

```
[lncli] rpc error: code = Unknown desc = socks connect tcp 127.0.0.1:9050->[removed].onion:9735: unknown error general SOCKS server failure
```
