### ISSUE TITLE
Latest LND with Older Bitcoind (v0.18.1.0)

### ISSUE THREAD

**Issue by Ajeeshb** [lightningnetwork/lnd#6430]
### Background

After upgrading to the latest lnd version (from 0.11.1_beta to 0.14.2-Beta) My https url is not working (https://<mylndnode>:10010)

### Your environment

* version of `lnd`
* 0.14.2-Beta
* which operating system (`uname -a` on *Nix)
* Ubuntu 16 LTS
* version of `btcd`, `bitcoind`, or other backend
* v0.18.1.0
* any other relevant environment details
I am running LND as a Dockerised version
### Steps to reproduce
While accessing the URL :: https://myip:16010/v1/getinfo
I am getting the following error.

{"code":2,"message":"expected 1 macaroon, got 0","details":[]}

But the same worked fine with the lnd version 0.11.1-Beta

**Comment by guggero** [comment]
That error message has nothing to do with `bitcoind`. You need to send a macaroon when calling an `lnd` REST endpoint. Not sure why this worked before, how does your `lnd` config look like?

**Comment by Ajeeshb** [comment]
I am passing it as environment variables in docker-compose file.

NB: URL :: https://myip:16010/v1/getinfo is a self-signed SSL, There is no SSL provided.

```
services:
  lnd:
    image: lnd_image:0.14.2-Beta
    hostname: lnd
    restart: unless-stopped
    ports:
      - "$lnd_http:10010"
      - "$lnd_rpc:10009"
      - "$lnd_port:9735"
    volumes:
      - lnd-data:/root/.lnd/
    networks:
      - workspace
      - default
    environment:
      DEBUGLEVEL: debug
    command: lnd --maxpendingchannels=10 --alias=${project}_lnd_1 --tlsextradomain=mydomain.com --tlsextraip=mylocalIP --externalip=public_ip:$lnd_port --listen=0.0.0.0:9735 --tlscertpath=/root/.lnd/tls.cert  --adminmacaroonpath=/root/.lnd/admin.macaroon --readonlymacaroonpath=/root/.lnd/readonly.macaroon --invoicemacaroonpath=/root/.lnd/invoice.macaroon --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:10010 --bitcoin.active --bitcoin.testnet --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoin:18332 --bitcoind.rpcuser=user --bitcoind.rpcpass=pass --bitcoind.zmqpubrawblock=tcp://bitcoin:28332 --bitcoind.zmqpubrawtx=tcp://bitcoin:28333
networks:

```
