### ISSUE TITLE
[feature]: Kubernetes example in the documentation

### ISSUE THREAD

**Issue by Slyke** [lightningnetwork/lnd#7367]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Kubernetes example. Should contain the required run commands, service, volume definitions, dealing with lock files etc.

**Describe alternatives you've considered**
None.

**Additional context**
I'm having trouble getting it to start with Kubernetes, or correctly restart. Here's what I got so far:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lnd
  name: lnd
  namespace: cryptocurrency
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: lnd
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lnd
    spec:
      initContainers: # <--- Are initContainers needed?
      - name: setup-lnd
        image: busybox:1.35.0
        imagePullPolicy: IfNotPresent
        command: ["Do I need something here to fix lock files?"]
        volumeMounts:
        - mountPath: /root/.lnd
          name: lnd-data
      containers:
      - env:
        - name: ServerIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: lnzap/lnd:v0.12.0-beta # <---- Should not use :latest
        command:
          - "what to put here?" # <---- Help needed
        imagePullPolicy: IfNotPresent
        name: lnd
        resources:
          requests:
            cpu: "10m"
            memory: "512Mi"
        volumeMounts:
        - mountPath: /root/.lnd
          name: lnd-data
        ports:
        - containerPort: 8080
          name: lnd-http
          protocol: TCP
        - containerPort: 10009
          name: lnd-rpc
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: lnd-data
          persistentVolumeClaim:
            claimName: lnd-data-pvc
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cryptocurrency
  labels:
    app: lnd
  name: lnd-data-pvc
spec:
  storageClassName: ""
  volumeName: lnd-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lnd
  name: lnd
  namespace: cryptocurrency
spec:
  externalTrafficPolicy: Local
  ports:
  - name: lnd-http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: lnd-rpc
    protocol: TCP
    port: 10009
  selector:
    app: lnd
  # loadBalancerIP: 192.168.1.5 # If using MetalLB
  type: LoadBalancer
```
